"""Add LLM configuration models

Revision ID: 245870892701
Revises: 001
Create Date: 2025-10-27 21:48:56.057986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245870892701'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

