name: Deploy to Azure

on:
  push:
    branches:
      - production
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE: chandrahoro-frontend
  BACKEND_IMAGE: chandrahoro-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Frontend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: chandrahoro-frontend
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE }}:latest

      - name: Deploy Backend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: chandrahoro-backend
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE }}:latest

      - name: Run Database Migrations
        run: |
          az webapp config appsettings set \
            --resource-group chandrahoro-prod \
            --name chandrahoro-frontend \
            --settings MIGRATE_ON_STARTUP=true

      - name: Verify Deployment
        run: |
          echo "Checking frontend health..."
          curl -f https://chandrahoro-frontend.azurewebsites.net/health || exit 1
          
          echo "Checking backend health..."
          curl -f https://chandrahoro-backend.azurewebsites.net/health || exit 1

      - name: Notify Deployment Success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Deployment to Azure successful!\n\n- Frontend: https://chandrahoro-frontend.azurewebsites.net\n- Backend: https://chandrahoro-backend.azurewebsites.net'
            })

      - name: Notify Deployment Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Deployment to Azure failed. Check logs for details.'
            })

